// Generated by https://quicktype.io

class Server {
  List<dynamic> cores;
  List<dynamic> disks;
  Map<String, double> packageId0;
  Map<String, String> date;
  List<String> disksName;
  int nCores;

  Server({
    this.cores,
    this.packageId0,
    this.date,
    this.disksName,
    this.nCores,
    this.disks,
  });

  Server.fromJsonMap( Map<String, dynamic> json ) {

    this.packageId0 = json['packageId0'];       
    this.date       = json['date']; 
    this.disksName  = json['disksName'];     
    this.nCores     = json['nCores'];   
    for(int i = 0; i <= this.nCores; i++ ){
      this.cores.add(json['Core $i']);
    }
    for(String i in this.disksName){
      this.disks.add(json[i]);
    }
  }
}


        
